services:
  - type: web
    name: angular-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/recommendation-system
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
